version: '3'
services:
    consumer:
        build: ./Consumer
        container_name: kfs-consumer
        links: 
            - kafka
    producer:
        build: ./Producer
        container_name: kfs-producer
        links: 
            - kafka
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: kfs-zookeeper
        ports: ["2181:2181", "2888:2888", "3888:3888"]
    kafka:
        image: wurstmeister/kafka
        container_name: kfs-kafka
        ports:
            - "9092:9092"
        links:
            - zookeeper
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_CREATE_TOPICS: "download-completed:1:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181